services:
  postgres:
    image: postgres:17

    container_name: estoque-postgres

    restart: unless-stopped

    environment:
      POSTGRES_USER: stock_user
      POSTGRES_PASSWORD: stock_123456
      POSTGRES_DB: stock_db

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
